import{a as v,S,i as c}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function m(s,t=1){const r={key:"51362272-d48daa27a05223f6096b84303",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await v.get("https://pixabay.com/api/",{params:r})).data}catch(n){throw console.log(n),n}}const f=document.querySelector(".gallery"),$=new S(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),y=document.querySelector(".js-loader"),h=document.querySelector(".load-more-button");function p(s){const t=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:i,comments:w,downloads:q})=>`
    <li class="gallery-item">
      <a href="${n}">
        <img src="${r}" alt="${e}" loading="lazy"/>
      </a>
      <div class="info">
        <p>Likes: ${o}</p>
        <p>Views: ${i}</p>
        <p>Comments: ${w}</p>
        <p>Downloads: ${q}</p>
      </div>
    </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function M(){f.innerHTML=""}function g(){y.classList.remove("is-hidden")}function L(){y.classList.add("is-hidden")}function b(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}const B=document.querySelector(".form"),P=document.querySelector(".load-more-button");let a=1,d="";l();let u=0;const O=async s=>{s.preventDefault(),M(),l();const t=s.currentTarget.elements["search-text"].value.trim();if(t===""){c.info({message:"Insert the search request."});return}d=t,a=1;try{g();const r=await m(d,a);if(u=Math.ceil(r.totalHits/15),r.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}p(r.hits),a<u?b():l()}catch(r){c.error({message:`Error: ${r.message}`})}finally{L()}},x=async()=>{a+=1,g();try{const s=await m(d,a);p(s.hits);const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}if(a>=u)return l(),c.info({message:"We're sorry, but you've reached the end of search results."});b()}catch(s){c.error({message:`Error: ${s.message}`})}finally{L()}};B.addEventListener("submit",O);P.addEventListener("click",x);
//# sourceMappingURL=index.js.map
